### ISSUE TITLE
Expose / remove the examples

### ISSUE THREAD

**Issue by craigdallimore** [ramda/repl#1]
Perhaps I'm missing something obvious, but I cannot see where the following becomes part of the repl:

[/examples](https://github.com/ramda/repl/tree/master/examples)
[create-examples.js](https://github.com/ramda/repl/blob/master/create-examples.js)
[lib/js/examples.js](https://github.com/ramda/repl/blob/master/lib/js/examples.js)

Along the same lines, `npm run build-examples` is not working as it relies on `babel-node` which is not present.

Happy to help out, but I'm not sure what is needed here (or if everything is as it should be).

**Comment by buzzdecafe** [comment]
i'll try and take a look tonight, I don't know yet either.

**Comment by buzzdecafe** [comment]
yup, let's chuck 'em.
