### ISSUE TITLE
Steps to take to make this the "Try Ramda" repl

### ISSUE THREAD

**Issue by craigdallimore** [ramda/repl#18]
At present there are two versions of the ramda repl being maintained as far as I can tell - this one, and the  one at [ramda.github.io](https://github.com/ramda/ramda.github.io). I presume we want this one to take over from that one.

Does anyone have particular thoughts/recommendations on how that should be arranged? Perhaps we just add in a link to the `bundle.js` in this repo and instantiate an instance?

**Comment by buzzdecafe** [comment]
>  I presume we want this one to take over from that one.

Yes; also, i think you have been working toward embedding the repl in the docs themselves to run the examples -- which would be great.

> Does anyone have particular thoughts/recommendations on how that should be arranged? Perhaps we just add in a link to the bundle.js in this repo and instantiate an instance?

Maybe. Not 100% clear to me yet, I will have to take a look. Maybe add repl as a dependency in ramda.github.io? In that case we would probably want to publish repl as its own package

**Comment by craigdallimore** [comment]
I've had some promising results using the githubs `rawgit` CDN to serve the CSS and JS from this repo on the _Try Ramda_ page. I'll make a PR for your inspection if #24 is accepted.
