### ISSUE TITLE
Calls to browserify CDN failing everywhere

### ISSUE THREAD

**Issue by Koleok** [ramda/repl#19]
Whether I build and run this locally, or actually visit the repl in the docs, for the last few days I have been seeing all the browserify CDN calls `404`s out for `sanctuary` and the other imported libs. This obviously ends the party right there, any one have the scoop on this?

**Comment by Koleok** [comment]
Update, it looks like this service is just down entirely, not scoped to any lib.

**Comment by buzzdecafe** [comment]
yup, see https://github.com/ramda/ramda/issues/1873
and https://github.com/jfhbrook/wzrd.in/issues/143
