### ISSUE TITLE
Development mode

### ISSUE THREAD

**Issue by craigdallimore** [ramda/repl#2]
If I load index.html in my browser from the filesystem it fails to load the following links:

```
file://wzrd.in/standalone/sanctuary@latest
file://wzrd.in/standalone/ramda-fantasy@latest
```
and as a consequence a `sanctuary is not defined` error occurs.

To help with development, I'd like to

- add `http-server` as per `ramda.github.io`
- add a `npm run dev` command for watching and re-bundling as files change
- add instructions for the above to the `README.md`

**Comment by buzzdecafe** [comment]
closed by #4
