### ISSUE TITLE
FR: Auto complete in web REPL

### ISSUE THREAD

**Issue by hemanth** [ramda/repl#26]
Autocomplete or tab complete on R.

![image](https://cloud.githubusercontent.com/assets/18315/19271710/7685ceca-8fe3-11e6-91aa-6f214479afe8.png)

[Reference](https://github.com/ramda/ramda.github.io/issues/31#issuecomment-141296705)

**Comment by craigdallimore** [comment]
Thank you for moving this @hemanth - do you mind adding some more detail on what needs to change?

Right now on [try ramda](http://ramdajs.com/repl/#?code=R.) if I type `R.` and press `<tab>` I get the pictured flyout.

I presume this is either not happening for you, or the interaction with the flyout is not right.

**Comment by hemanth** [comment]
Ha, that issue was great looong ago, nice to see the tab completion, closing this for now, thanks!
