### ISSUE TITLE
REPL not working?

### ISSUE THREAD

**Issue by exiadbq** [ramda/repl#43]
Error: Failed to load http://wzrd.in/standalone/sanctuary@latest

and in console:
`bundle.js:52936 GET https://wzrd.in/standalone/sanctuary@latest net::ERR_INSECURE_RESPONSEload @ bundle.js:52936(anonymous function) @ bundle.js:354(anonymous function) @ bundle.js:63302(anonymous function) @ bundle.js:63302(anonymous function) @ bundle.js:63273(anonymous function) @ bundle.js:63304(anonymous function) @ bundle.js:63233(anonymous function) @ bundle.js:63290(anonymous function) @ bundle.js:63304(anonymous function) @ bundle.js:63233(anonymous function) @ bundle.js:355script.onload @ bundle.js:52948
bundle.js:52936 GET https://wzrd.in/standalone/ramda-fantasy@latest net::ERR_INSECURE_RESPONSE`

**Comment by davidchambers** [comment]
Thanks for letting us know. Let's track this in ramda/ramda.github.io#156.
