### ISSUE TITLE
Remove navigation bar

### ISSUE THREAD

**Issue by craigdallimore** [ramda/repl#5]
If I understand correctly, an objective is to make this REPL embeddable so it can be included within the documentation example sections and in the "Try Ramda" page (and perhaps other places).

This suggest to me that it shouldn't carry around the navigation; that could belong to the page that _contains_ the REPL.

**Comment by buzzdecafe** [comment]
sounds completely reasonable to me. I think we can also jettison the "examples/" directory.

**Comment by craigdallimore** [comment]
On it.
