### ISSUE TITLE
Rawgit 404 for ramda resources

### ISSUE THREAD

**Issue by PBM42** [ramda/repl#53]
Error failed to load resources from rawgit (404) for 
https://cdn.rawgit.com/ramda/repl/1.1.0/dist/bundle.js and
https://cdn.rawgit.com/ramda/repl/1.1.0/dist/bundle.css

**Comment by CrossEye** [comment]
Sorry, we forgot to tag a release.  It's running now.

**Comment by davidchambers** [comment]
> Sorry, we forgot to tag a release.

This project should use [xyz][1]. ;)


[1]: https://github.com/davidchambers/xyz
