### ISSUE TITLE
Ramda/repl loads up ages

### ISSUE THREAD

**Issue by Mati365** [ramda/repl#60]
https://ramdajs.com/repl/?v=0.25.0 loads something about 15s.

**Timeline:**
![Timeline](https://i.imgur.com/xVPZkij.png)

**Comment by CrossEye** [comment]
I've been  noticing this for two weeks or so, and haven't had time to investigate.  We've had problems before when wzrd.in has been very slow.  If anyone knows something about alternatives, I think it's past time when we try using something else.

**Comment by Rafi993** [comment]
I created a simple repl similar to this one using monaco editor https://rafi993.github.io/repl/.  Rather than using a general lib I made it more specific.

**Comment by CrossEye** [comment]
(Sorry for the slow reply: just back from vacation.)

That's very nice to see.  I will try to look at it more closely over the next few days.

**Comment by Rafi993** [comment]
It seems that these are the two scripts that take really long time to load
https://wzrd.in/standalone/ramda-fantasy@latest
https://wzrd.in/standalone/sanctuary@latest
other network request are resolved quickly. We can try replacing them with cdnjs links (since other scripts are loaded from cdnjs).

**Comment by davidchambers** [comment]
<https://sanctuary.js.org/#installation> lists the required scripts in the correct order.

**Comment by Rafi993** [comment]
Is there any updates on this ?

**Comment by Rafi993** [comment]
I replaced these two files https://wzrd.in/standalone/ramda-fantasy@latest
https://wzrd.in/standalone/sanctuary@latest with a local js. It took around 1.07s to load.

![2018-11-22-182031_1366x768](https://user-images.githubusercontent.com/8092120/48904165-8f790680-ee83-11e8-9d24-df743193e5b7.png)

**Comment by CrossEye** [comment]
@Rafi993: Would you like to make a PR for those changes?

**Comment by Rafi993** [comment]
I have created this pull request https://github.com/ramda/repl/pull/62 we can use it for now. But it would be better if we can create cdnjs for both of those files.

**Comment by CrossEye** [comment]
I merged that request as a temporary fix.  I will try to republish this evening.

**Comment by CrossEye** [comment]
Build errors.  I'm on a mobile device right now, but when I get in front of a computer again, I will try again and post the errors somewhere if I don't get it to work.

**Comment by foxbunny** [comment]
I'll be available next weekend to try and assist if you still need help then.

**Comment by CrossEye** [comment]
Thank you.  After spending as long as I did on the big release ten or so days ago, and having everything eventually work, when this didn't work, I stopped in frustration and haven't really gone back to it.

**Comment by CrossEye** [comment]
Those fixes are up, and it seems to load much faster!

**Comment by Rafi993** [comment]
The repl still seems to refer to https://wzrd.in/standalone/sanctuary@latest and https://wzrd.in/standalone/ramda-fantasy@latest was it deployed ?

**Comment by CrossEye** [comment]
Not sure what happened.  I swear it was working last night...

Uggh!

**Comment by meszaros-lajos-gyorgy** [comment]
`wzrd.in` has been ditched and content is now served from `bundle.run`. It is blazing fast now. Since https://github.com/ramda/ramda.github.io/issues/217 is resolved, I suggest the same for this ticket.
