### ISSUE TITLE
Share links broken in Safari

### ISSUE THREAD

**Issue by nateabele** [ramda/repl#61]
I'm not sure if this is a goo.gl issue or something with the REPL itself, but share links don't retain the `#` (or anything after it) on redirect in Safari.

**Comment by CrossEye** [comment]
(Sorry for the slow reply: just back from vacation.)

We're going to have to switch to a new minifier, as goo.gl is shutting down.  It's on the list!

**Comment by zehua** [comment]
This is now fixed.

**Comment by nateabele** [comment]
Thanks!
