### ISSUE TITLE
Repl unusable

### ISSUE THREAD

**Issue by mendrik** [ramda/repl#68]
Seem to be stuck on loading  https://bundle.run/ramda-fantasy@0.8.0 and one more script from there.
Share button is also broken.

**Comment by CrossEye** [comment]
Yes, this came up recently and was fixed, presumably by bundle.run, and then broke again,  I meant to look at it the other evening, but didn't manage to find the time.  I will try again this weekend.

I think it will involve moving away from bundle.run.  But I'll take a look.
