### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by craigdallimore** [ramda/repl#9]
If we wish to reuse this on pages other than http://ramdajs.com/repl/ we might need to address some of these aspects - perhaps using some kind of configuration:

- The google shortlink has an API KEY that relates to the above address; I presume we would want to configure it and the address rather than have them hardcoded.

- We may not always want / need to update the address bar with the content of the input panel - this makes sense for sharing, but I'm not sure how it should work if we wish to reuse the repl to make dynamic examples on the docs page. I'd suggest that for those we could configure it to make a shortlink back to `http://ramdajs.com/repl/` (or not at all).

**Comment by buzzdecafe** [comment]
I agree completely with both points

**Comment by CrossEye** [comment]
:herb:
